### PR TITLE
set of changes for the scrutinizer configuration

### PR DESCRIPTION
**Pull request by dmill-bz**
_Not ready to be merged_
Setting this here to run it against Scrutinizer. 
Should I also go ahead and change travis to check `PHP 5.6` only as well?

### CODE REVIEW

**Comment by electricjones** [comment]
Yeah, let's just do `5.6`, `7`, and `hhvm`

**Comment by dmill-bz** [comment]
Ok so I've made it so that **PSR-2** is the standard used for checking the code. I'm not sure how well this is being carried out as I still see some PSR-2 standards in the "not enabled" checks. This might be because I configured code sniffer directly. Anyways, It won't hurt to have some redundant checks so on top of this here's what I suggest we add as extra checks (check them off if you agree):
- [x] Check that `self` is used in place of fully qualified names
- [x] Check that constants are in `UPPER_CASE`.
- [x] Check the types of `@return` doc comments 
- [x] Check whether the return type is inferable and ask for a `@return` comment if not
- [x] Check that properties are named in camelCaps format (_I don't know if this interferes with private `_` prefixed properties. We could always disable it later._)
- [x] Check that parameters are named in camelCaps format
- [x] Check whether parameter types are inferable and ask for a `@param` comment if not (should mostly cover missing `@param` and not suggest what they should be
- [x] Check that optional function parameters are defined at the end 
- [x] Check that files end with a new line character
- [x] Check that function names are in camelCaps format 
- [x] Fix use statements 
- [x] Check that class names are in CamelCaps format
- [x] Check that Perl-style comments (# Some comment) are not used
- [x] Check there are not multiple statements on the same line (e.g.: `blah;blah;`)

Again, some of these should already be covered by **PSR-2** checks, no harm in making them redundant.

**Comment by dmill-bz** [comment]
Oh and I place 7.0 as an allowed failure (as some of the dependencies fail).

**Comment by electricjones** [comment]
Looks great. Should raise our score by default. Thanks for the work.

**Comment by dmill-bz** [comment]
I'm not sure the score will increase. Usually the score is related to cyclomatic complexity, potential bugs, structure of classes (abstract, or if there are too many private/protected methods, etc.). So it should stay roughly the same. But at least we won't have constant unrelated nagging from scrutinizer.

**Comment by dmill-bz** [comment]
ok all tests pass I'm going to merge this

**Comment by smolinari** [comment]
:+1: 

Scott

**Pull request merged**
