### PR TITLE
change gremlin-server version for vagrant to 3.0.2, added composer.lock

### PR DESCRIPTION
**Pull request by dmill-bz**
@chrismichaels84 can you just double check the sanity of the vagrant changes? I can't really test vagrant in my env yet (will try to get it up and running)

### CODE REVIEW

**Comment by dmill-bz** [comment]
Or @smolinari if you get a chance to test vagrant on this.

**Comment by dmill-bz** [comment]
@smolinari does this work in the end? can I merge this branch or do changes need to be made?

**Comment by smolinari** [comment]
@PommeVerte - yes. It is working fine. I think the issue I had yesterday afternoon was caused by a flaky internet connection and somehow screwed up the Gremlin install. This morning all worked as it should on the Gremlin/Neo4j side.

Scott

**Comment by dmill-bz** [comment]
ok awesome. adding this then :)

**Comment by smolinari** [comment]
Theoretically, if Chris accepts my changes (plus some needed cleanup work), then we'd also have ODB up to 2.1.6 too. 

Scott

**Pull request merged**
