### PR TITLE
Adds a vagrant box for easier sharable development

### PR DESCRIPTION
**Pull request by electricjones**
This adds a [Vagrant](http://vagrantup.com/) box to easily get a virtual environment setup with all the test databases. See docs/contributing.md for more details.

There is probably a way to share the CI and Vagrant folders, but I didn't look at it too closely.

### CODE REVIEW

**Comment by dmill-bz** [comment]
wow awesome. I'll have to take a closer look at this

**Comment by dmill-bz** [comment]
This looks good and quite straightforward. Wondering about possible docker use now.
Anyways it gets my +1

**Comment by electricjones** [comment]
I am not familiar with docker, but anything that can help us (and others) focus on development and not environment is a plus for me. I'm going to go ahead and merge this into `develop`

**Comment by smolinari** [comment]
@PommeVerte - glad you are ok. Still in Paris aren't you?

Scott

**Comment by dmill-bz** [comment]
Yeah, everything's fine here. Quite a crazy night we had on friday

**Pull request merged**
