### PR TITLE
Migrate to Docker from Vagrant

### PR DESCRIPTION
**Pull request by electricjones**
Picking up on Issues #120 and #123 . **This is not ready to merge yet**

Alright, after a lot of learning, I managed to create a setup that works for orientdb for now. It should be easy enough to add neo and gremlin.

clone the `docker` branch
`docker-compose up -d`
`docker run -it --link spider_orientdb:orientdb --net spider_default -v /Mac/users/michael/code/spider/spider:/spider spider/php bash`

The second command is specific to my system. replace the `/mac/users...` path with the absolute path of spider. (for windows /c/path/to/spider).

This will all be abstracted away beneath a `spider-dev.sh` bash file. After a long chat with a coworker who manages our docker system, I think it'll be best to skip `docker-compose` for now. If we do everything through `docker build` and `docker run` abstracted behind a `spider-dev` bash file, then we give the users the ability to cherry pick and mix-and-match the versions of php and database.

Also, I had to use a php image from `ubuntu:15.10` which I hate. It's huge. I tried several others, but got frustrated b/c I either couldn't install xdebug or they weren't compiled with sockets enabled (I can't figure out why). I am sure there exists, or we can define a better one. For now, though, I just wanted to get it working.
## Still ToDo:
- [x] Remove vagrant
- [x] Setup PHP and Orient to work with shell
- [x] Move fixture and testing credentials to `.env` file (that's why tests fail right now)
- [X] Add Neo4j
- [x] Add Gremlin
- [x] Add a php 5.6 container
- [x] Add versioning for supported versions to `docker-compose.yml` (https://docs.docker.com/compose/compose-file/#variable-substitution)
- [x] Initialize `spider-dev.sh` to abstract away docker commands (from #123)
- [x] Add testing commands to `spider-dev` (`spider-dev test -iau`)
- [x] Integrate with Travis
- [x] Documentation and lots of testing

### CODE REVIEW

**Comment by electricjones** [comment]
Neo4j and OrientDB are up and running. I ran into some problems adding the Gremlin container. Will try later this week.

To get this running at this point:

``` bash
docker-compose up
docker run -it --link spider_orientdb:orientdb --link spider_neo4j:neo4j --net spider_default -e "SPIDER_DOCKER=true" -v /Mac/users/michael/code/spider/spider:/spider spider/php bash
```

Replacing the volume path with your own. The next step is to get `docker-compose.yml` to handle these complexities and multiple versions of databases and php.

**Comment by smolinari** [comment]
The only way I can see a `docker-compose.yml` handle different versions is to have different `docker-compose.yml` files with a different base `dockerfile`.  

I've been working with Docker now too the last couple of days and learning a lot. :smile: I've also gotten a PHP image created with Alpine Linux with PHP7 and it has composer + phpunit globally pre-installed. You can get the image with 

`FROM skooppaos/php7`

I can easily create a php5.6 image too. Would we need any other PHP versions?

Scott

**Comment by electricjones** [comment]
That's great! does that php container come with sockets enabled? The last time I tried an alpine container, I couldn't get sockets to work, which is ridiculous. I think 5.6 and 7.0 are all we are really supporting right now. It would be great to have them both installed on the same container, but two different boxes would be fine as well.

And `docker-compose.yml` supports [Variable Substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) which I think should do the trick. Actually, if we push a working php container to hub.docker.io, then we won't need any dockerfiles whatsoever.

**Comment by smolinari** [comment]
I have sockets enabled in the PHP compilation. Is that what you mean?

Scott

**Comment by electricjones** [comment]
Yes, that is exactly what I mean. Thank you.

**Comment by electricjones** [comment]
And, I take it back. Two different tags (`FROM skooppaos/php:7.0`, `FROM skooppaos/php:5.6`) or something similar would be perfect. Also, would you consider making that repo public on github? I'd like to see the Dockerfile, and others may as well.

**Comment by smolinari** [comment]
Ok. I'll push them with those tags. 

It isn't as easy as I thought to make a 5.6 image. Working on it though.

Scott

**Comment by electricjones** [comment]
Your container worked great.

I have also simplified what is needed to run the containers:

`docker-compose run php sleep 15;phpunit` will run all the phpunit tests

The first time you run it, it will pull in and build everything. The "sleep 15" needs a better solution. The php container cannot start running its tests until the db services are up and ready. The best alternative (though more complex than I like) is to have the php bootstrap file check for connections, and hold up the tests until the connections are good.

I'd love to find a better solution.

To open a full terminal, you must still

``` bash
docker-compose up -d
docker run -it --link spider_orientdb:orientdb --link spider_neo4j:neo4j --net spider_default -e "SPIDER_DOCKER=true" -v /Mac/users/michael/code/spider/spider:/spider spider/php bash
```

Also open to a better solution here.

One last note: I have moved all the credentials to environment variables. This means you can use the docker's php container, or use php locally. Simply add a `.env` file to the spider root with the services credentials and you can run the tests and such from your host machine. For me, this was a huge performance boost.

**Comment by electricjones** [comment]
I have pushed a basic shell script to handle docker testing and management. I'm happy with it, though I'm sure it could use some refactoring and testing.

See `bin/spider-dev` for api.

From spider directory `bin/spider-dev test` to run all tests, `bin/spider-dev up` to start services, etc.

**Two important notes**
- If you (like me) are using the docker private beta for mac, you must include the flag `--mac` for now. This will be removed once beta goes out.
- The options MUST come before the command. At least for now.

@smolinari Have you gotten any luck with a php5.6 container? I also noticed that this one doesn't support bash or shell. At least not that I've found. We need a way to do something like

`docker run -it skooppaos/php7 bash` and open up a terminal.

Next step is to finish versioning in the `docker-compose` file, and then add gremlin support.

**Comment by smolinari** [comment]
@chrismichaels84 - I haven't finished the 5.6 version yet. Working on it today. The php7 version is also finished and coincidentally, I also added bash, because of the timeout issue I'm having with ODB (which you also mentioned), I was trying to incorporate [wait-for-it](https://github.com/vishnubob/wait-for-it). So the new image should work for you now. It is also under `skooppaos/php:7.0` as you wished.

I like the script you made. I guess I'll have to test it. :smile:  

Edit: I've also uploaded the files to a repo: https://github.com/skooppaos/docker-files

Edit2: I actually won't be getting the 5.6 version done today. I had too much work on my house and now I have to go shopping for the weekend. So, I'll get to it tomorrow.

Scott

**Comment by electricjones** [comment]
The container looks great. Good work. And wait-for-it could come in handy. I've run into a problem where I have to make containers sleep before running tests b/c we have to wait for the databases to be ready. Something like this could be super helpful. And have a good weekend.

**Comment by electricjones** [comment]
Just pushed update with full-ish versioning control. If you try to use an unsupported version, you will get an error, but it will let you try. If there is a docker image with that tag, it will load.

Also added `spider-dev versions` which prints some info.

Does NOT include actual supported versions. That will have to be its own ticket to see what spider actually supports. This way, though, we get to keep each branch and its supported versions together, which is nice.

Last cleanup items before this gets tested and merged (other than documentation)
- [x] Some simple refactoring
- [x] Better handling of working directories
- [x] Add gremlin container

Would be nice:
- [x] ~Integrate `wait-for-it` so that `spider-dev` doesn't run tests or open a shell until the environment is ready. I first thought to do this is phpunit, but I think those tests _should_ fail if the service is unavailable.~ This deserves its own ticket and is unimportant atm.

My last thought is along with #123, add a `spider.php` cli utility with a command to build this bash file automatically from a `supported_versions.json` file or something similar. We can use the same meta file in Travis or anything else. One place to change whatever.

**Comment by smolinari** [comment]
Just an FYI. Spider can't support ODB 2.2 yet, because the OrientPHP driver doesn't work properly with 2.2, unfortunately. 

https://github.com/Ostico/PhpOrient/issues/71
https://github.com/orientechnologies/orientdb/issues/6143

Scott

**Comment by smolinari** [comment]
The skooppaos/php:5.6 image is finished and pushed to Docker-hub. It took way too long to do too. I had a compile error and had finally found out the 5.6.21 src on Github is broken (bson version wasn't being accepted), so I used the php.net archive. Don't ask me how I ended up with finding that as the answer, but I did. It just took an incredibly long time to get there. 

I'll test out the whole Docker setup tomorrow morning. 

Scott

**Comment by electricjones** [comment]
Great work.

I think all that leaves is the broken gremlin container and getting the integration with travis right.

@PommeVerte could you take a look at the gremlin container? The docker-compose.yml file has two containers commented out. The first one is yours. When it is active, it builds fine, but when we try to run the tests, the gremlin tests fail, saying the connection was refused. The hostname is "gremlin" and pinging "gremlin" and "gremlin:8182" both work fine. Not sure if the server is failing to start for some reason?

For the moment, the gremlin tests are marked as skipped.

**Comment by electricjones** [comment]
Integration with travis is complete, minus the Gremlin container.

HHVM seems to be failing, but its failing on the very first (Travis-specific) command, so it may be a but in their system. I'll look at it tomorrow.

**Comment by smolinari** [comment]
Bad news. Docker sucks under Windows 7. There is no interactive mode, so the php container just stops and nothing happens. I also can't get volumes to work.  I've reworked (back) in a dockerfile, so I can work with the spider_php image, but that also doesn't help. When I run the container with `run -it`, the  `/spider` directory is empty. I've looked up stuff about volumes with Windows and setting them up
with Virtualbox, but nothing seems to work.  I can copy the files into the container, but then phpunit doesn't work. It doesn't show any errors, nothing. I am lost. It seems my only solution to fix this is moving to Win10. Yuck! :cry: 

Edit: Ha! Look what I found. 

http://stackoverflow.com/questions/37194404/phpunit-not-displaying-error-output-in-docker-container

Same issue I have now, when running the container interactively.  

Scott

**Comment by smolinari** [comment]
Ok. From your SE post, I got an idea and now I have some output.

`No Database Credentials Supplied. Please use the supplied docker container or add a .env file.`

Could it be a compatibility issue with phpunit? The global phpunit installed in the PHP containers is 5.0. The one used in spider is 4.8.

Scott

**Comment by electricjones** [comment]
Yep, that's actually my question, lol. I thought I had fixed that, at least on mine.

The credentials exceptions is actually part of spider. I forgot to document that. When you want to use php on your machine and just connect to the databases, you need to add a `.env` file to the spider directory that looks like `tests/.env.docker` but with your credentials (usually "localhost" for the hostnames, everything else should be the same).

If you are getting that error from one of the spider-dev commands (like `bin/spider-dev shell`) then an environment variable is not being set. The cli utility sets `SPIDER_DOCKER` so the bootstrap file in phpunit knows which `env` file to load the db credentials from.

**Comment by electricjones** [comment]
And I figured docker in windows and mac would suck. I was hoping not so much. I'm really waiting for https://beta.docker.com/ to go public. That's full native docker in windows and mac so it works exactly like linux.

**Comment by smolinari** [comment]
Yeah, but the "native docker" in Windows will only work with Win10. :cry: 

Scott

**Comment by electricjones** [comment]
Bummer. I hadn't realized that. The containers should still work, and you should be able to use the databases. But PHP would have to be installed on your computer, or you should be able to setup something like PHPStorm to use the php container to send remote commands.

In either case, even with no interactive capabilities, the `spider-dev test` command should still work.

**Comment by smolinari** [comment]
That's the problem. When I use `spider-dev test`, docker returns with

`ERROR: Interactive mode is not yet supported on Windows.`

I think I have a way to get around this. But, it would entail going back to a dockerfile to build the PHP service.

Scott

**Comment by electricjones** [comment]
That's weird. There is no interactive flag in that command. It's basically the same as running
`docker-compose up`
`sleep 30`
`docker-compose run php vendor/bin/phpunit`

Whenever you get a chance, I'd like to see what you arrive at as a workaround. If needed, we can create a separate `bat` file for windows, update the `sh` file, or just keep vagrant around for windows < 10. I didn't upgrade to 10 either.

**Comment by electricjones** [comment]
This probably doesn't help the windows problem, but a general improvement.

The `test` command now returns the exit code from phpunit, so you can run it in a more automated way.

The travis build fails b/c hhvm does not seem to be supported on docker builds of php. I have to do some research to figure that out. One option is to use `spider-dev test` command AS the test command, now that it returns the correct exit code. Question is, how to manage different php versions for different builds.

**Comment by electricjones** [comment]
I've opened up a ticket on Travis to see if they will support hhvm. The other option (which we should probably do anyway) is to officially add an hhvm image to the list and allow people to choose hhvm from `spider-dev`. Then, we could forgo using travis's language feature altogether and run the tests directly from our own docker container.

Ticket is travis-ci/travis-ci#6091.

**Comment by electricjones** [comment]
Well, Travis CI says hhvm is not supported with docker and they don't plan to. Looks like we should add an hhvm container.

**Comment by electricjones** [comment]
I have added hhvm to the environments, and updated the travis.yml file to use docker for everything. However, for some reason, my committs aren't pushing to github. Super weird.

**Comment by electricjones** [comment]
And that's basically it! I have added HHVM and done some final cleanup. Travis is now integrated to use the docker machines and we can have as many combinations as we like.

All that's left is to get the gremlin container working. I may take a stab at it tomorrow. I don't know why I've been having problems with it :/

@smolinari If we can't get this to work on windows/mac without the native app, then I vote we direct users to your spider-box for those instances. It has everything that's need and is known to work well. I've added some documentation in docs/contributing.md. Feel free to add/edit anything in the spider box section.

**Comment by smolinari** [comment]
Yup, I can't get Docker to do as I want on my Win7 system and I've tried all sorts of things. I am giving up, which I hate to do. I guess I'll stick with Vagrant for now as you suggest. 

The only thing missing is PHP7 support in the spider-box. I'll see if I can add that in the near future.

Scott

**Comment by electricjones** [comment]
Well, this is actually working -- and all finished with gremlin and all -- but there are two external problems:
- [ ] The Gremlin container does not work with transactions. I have opened a ticket PommeVerte/docker-gremlin-server#2. For now, that one test is skipped for gremlin
- [ ] Travis seems to be having trouble with the neo container. However it all works locally.

**Comment by electricjones** [comment]
So, I've run into a really weird problem. It seems that (only on travis) the neo4j tests can't connect to neo4j when the gremlin database is running. Works fine on my local machine. When the gremlin db is disabled, all works well. Even when the gremlin tests are skipped -- if the db is up, then neo4j isn't.

But only on travis.

@PommeVerte any idea what may be causing this?

**Comment by electricjones** [comment]
I have decided to revert to a point where everything is working except gremlin, merge this into develop and then into the other two PRs. This will allow me to use it in real situations for testing.

We just have to be sure not to release develop until the gremlin container is working as expected. If I find myself with time and @PommeVerte isn't able to look at it, I may fork the gremlin container and see what I can do. I need to learn tinkerpop better anyway.

**Pull request merged**
