### PR TITLE
initial implementation of gremlin-server driver

### PR DESCRIPTION
**Pull request by dmill-bz**
This code is functional and the tests pass (though the tests aren't more rigorous than the Orient ones)

This could be optimized and I made a post in one of the issues with some points I wanted to bring up. This PR is the code to go with those points. 
I might create an issue for each point so we can follow them separately and go into more detail.

### CODE REVIEW

**Comment by dmill-bz** [comment]
I still need to properly update commentblocks for this. Just a heads up.

**Comment by dmill-bz** [comment]
also if you want to run the tests you can just follow the installation instructions for unit tests [here](https://github.com/PommeVerte/gremlin-php#unit-testing) (conf files)

**Comment by electricjones** [comment]
I'm good to merge this, but do you want to wait until we've resolves some things in #7 and/or re-namespaced? Or is it better to merge now, and clean that up as later this week?

**Comment by dmill-bz** [comment]
It would probably be best to merge the driver configuration branch first. Then I'll rebase this and we can merge it.

**Comment by electricjones** [comment]
I have renamespaced the `develop` branch and merged `driver-configuration` into develop. All tests pass.

The last major refactor (that would likely affect this) is #15. Some of the DriverInterface API may change as we use consistent terms.

**Comment by dmill-bz** [comment]
I'm going to close this and remake the PR against the develop branch (can't seem to change it here)

**Pull request closed without merging**
