### PR TITLE
Merge Develop into Master (v0.3)

### PR DESCRIPTION
**Pull request by electricjones**
See changelog for full details.
- Adds command builder
- Unifies drivers
- Adds response formats
- Cypher and Neo4j language processors

### CODE REVIEW

**Comment by electricjones** [comment]
This is ready for release, there being no objections.

Going once....going twice...

**Comment by dmill-bz** [comment]
looks like we have conflicts somehow

**Comment by electricjones** [comment]
Alright, the conflicts are super minor. I updated the composer.json file and a couple readmes when I tranfered the repo and didn't merge them back into develop. Now, develop is correct. The build failed, but it wasn't failing tests, it was a failure to install gremlin-server.

I tried again, but I think I'm just gonna merge this soon.

Question to you: are you using any of the other branches? I like to delete `develop` and all the feature branches after a release, just to have a clean slate. Any objections? Any you want to keep alive?

**Comment by electricjones** [comment]
It seems like travis is hanging up on installing gremlin.

**Pull request merged**
